sudo: required
language: java
jdk:
  - oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - docker

addons:
  sonarcloud:
    organization: "mishco-github"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io

