server:
  port: 8080
spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false


logging:
  level:
    org:
      springframework: INFO